// Code generated by logcopter-gen; DO NOT EDIT.

package cozocgo

import logcopter "github.com/go-go-golems/logcopter/pkg/logcopter"

var log = logcopter.Package("go-go-golems.cozodb-goja.pkg.cozoapi.cozocgo")
